### PR TITLE
Fix Mouse Processing and Non-Virtual Functions for Maps

### LINKED ISSUE #47: Mouse needs to have its state updated before processing on the map
https://github.com/thesadrogue/TheSadRogue.Integration/blob/370c21aa240db9733f928310efb2fbb40a7a4bb0/TheSadRogue.Integration/Maps/RogueLikeMapBase.IScreenObject.cs#L41

Since the `RogueLikeMap` is a `ScreenObject` it has no concept of size. It just exists at a point in SadConsole screen space. Currently the mouse method is being forwarded to the `BackingObject`, however, the mouse state data is based on the map screenobject and not the `BackingObject`, it needs to be transformed.

```csharp
public bool ProcessMouse(MouseScreenObjectState state)
{
    state = new MouseScreenObjectState(BackingObject, state.Mouse.Clone());
    BackingObject.ProcessMouse(state);
}
```

### PR DESCRIPTION
**Pull request by Chris3606**
- Transformed mouse state as needed.  Fixes #47.
- Made appropriate functions of the map `IScreenObject` implementation virtual so a user can override them as intended

### CODE REVIEW

File: TheSadRogue.Integration/Maps/RogueLikeMapBase.IScreenObject.cs [hunk 1]
```diff
@@ -35,20 +35,47 @@ public abstract partial class RogueLikeMapBase
...
+            state = new MouseScreenObjectState(BackingObject, state.Mouse.Clone());
+            LostMouse(state);
+        }
+
+        /// <summary>
+        /// Overridable implementation of IScreenObject's LostMouse which is guaranteed to receive a mouse state
+        /// appropriate for the map implementation.
+        /// </summary>
+        /// <param name="state"/>
+        protected virtual void LostMouse(MouseScreenObjectState state) => BackingObject.LostMouse(state);
```
Comment (Thraka) [inline TheSadRogue.Integration/Maps/RogueLikeMapBase.IScreenObject.cs:71]: This one I think you don't need to actually transform it. I believe (scanning through the code yesterday but not really playing with it) I noticed that the state sent to `LostMouse` is the state for whatever object stole the mouse, or in the case of leaving the window, I believe it's a state that has a `null` screen object reference. So this can be restored and just made virtual

```suggestion
        public virtual void LostMouse(MouseScreenObjectState state) => BackingObject.LostMouse(state);
```

**Review by Thraka — APPROVED** [review]
Looks good. Just the one minor thing I noted.

**Comment by Chris3606** [comment]
> Looks good. Just the one minor thing I noted.

Fixed, thanks!

**Comment by Chris3606** [comment]
Only outstanding conversation on this is captured in #51 .  Merging.
